// <auto-generated />
using AuthenticationService.Entity;
using AuthenticationService.Web.Entity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace AuthenticationService.Context
{
    public class AuthenticationContext : IdentityDbContext<User>
    {
        public AuthenticationContext(DbContextOptions<AuthenticationContext> options)
            : base(options)
        {

        }

        public DbSet<Role> Roles { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var roles = new List<Role>
            {
                new Role { Id = $"{Guid.NewGuid()}", Name = "User", Description = "Default role of a user of GGC" },
                new Role { Id = $"{Guid.NewGuid()}", Name = "TwitterBotAdmin", Description = "Maintainer of the TwitterBot" },
            };

            modelBuilder.Entity<Role>().HasData(roles);
            base.OnModelCreating(modelBuilder);
        }
    }
}
